sudo: required
services:
 - docker

before_install: 
 - docker build -t chlaache/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true chlaache/react-test npm test

after_success:
 - docker build -t chlaache/multi-client ./client
 - docker build -t chlaache/multi-nginx ./nginx
 - docker build -t chlaache/multi-server ./server
 - docker build -t chlaache/multi-worker ./worker

