name: Deploy Complex
on:
  push:
    branches:
      - master
    
permissions:
  id-token: write
  contents: write

jobs:
  test:
    name: deploy apps
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build client
        run: docker build -t christofferlaache/multi-client ./client
      - name: Build nginx
        run: docker build -t christofferlaache/multi-nginx ./nginx
      - name: Build server
        run: docker build -t christofferlaache/multi-server ./server
      - name: Build worker
        run: docker build -t christofferlaache/multi-worker ./worker
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_ACCOUNT_NAME }}
          password: ${{ secrets.DOCKER_PWD }}
      - name: Push client
        run: docker push christofferlaache/multi-client
      - name: Push nginx
        run: docker push christofferlaache/multi-nginx
      - name: Push server
        run: docker push christofferlaache/multi-server
      - name: Push worker
        run: docker push christofferlaache/multi-worker

