name: Push Complex docker images and deploy
on:
  push:
    branches:
      - master
    
permissions:
  id-token: write
  contents: write

jobs:
  test:
    name: push and deploy docker images
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build client
        run: docker build -t christofferlaache/multi-client ./client
      - name: Build nginx
        run: docker build -t christofferlaache/multi-nginx ./nginx
      - name: Build server
        run: docker build -t christofferlaache/multi-server ./server
      - name: Build worker
        run: docker build -t christofferlaache/multi-worker ./worker
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_ACCOUNT_NAME }}
          password: ${{ secrets.DOCKER_PWD }}
      - name: Push client
        run: docker push christofferlaache/multi-client
      - name: Push nginx
        run: docker push christofferlaache/multi-nginx
      - name: Push server
        run: docker push christofferlaache/multi-server
      - name: Push worker
        run: docker push christofferlaache/multi-worker
      - name: Checkout code from repo
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_ACCOUNT_NAME }}
          password: ${{ secrets.DOCKER_PWD }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-west-1"
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      - name: Deploy
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          existing_bucket_name: "elasticbeanstalk-eu-west-1-727849506101"
          environment_name: "multidocker-env"
          application_name: "multidocker"
          region: "eu-west-1"
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip

